version: '3'
services:
  harmonizome:
    build: .
    image: maayanlab/harmonizome:1.0.16
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
